# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donnees_perso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('lieu_geo_lat', models.FloatField()),
                ('lieu_geo_long', models.FloatField()),
                ('temps_rappel', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='participe_evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDstyle.Evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('numero_tel', models.PositiveIntegerField()),
                ('possede_appli', models.BooleanField()),
                ('position_actuelle_lat', models.FloatField()),
                ('position_actuelle_long', models.FloatField()),
                ('dernire_position_lat', models.FloatField()),
                ('derniere_position_long', models.FloatField()),
                ('temps_position_active', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='participe_evenement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDstyle.Utilisateur'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_createur', to='BDstyle.Utilisateur'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(through='BDstyle.participe_evenement', to='BDstyle.Utilisateur'),
        ),
        migrations.AddField(
            model_name='donnees_perso',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDstyle.Utilisateur'),
        ),
    ]
