# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDstyle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='dernire_position_lat',
            new_name='derniere_position_lat',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_tel',
            field=models.CharField(max_length=10),
        ),
    ]
