# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDstyle', '0003_auto_20160110_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='adresse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_position_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_position_long',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_tel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='position_actuelle_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='position_actuelle_long',
            field=models.FloatField(blank=True),
        ),
    ]
