# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDstyle', '0004_auto_20160110_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='temps_position_active',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
