# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDstyle', '0006_auto_20160110_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='position_actuelle_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='position_actuelle_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
