# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDstyle', '0007_auto_20160110_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_position_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_position_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
