# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDstyle', '0008_auto_20160110_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participe_evenement',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='participe_evenement',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(to='BDstyle.Utilisateur'),
        ),
        migrations.DeleteModel(
            name='participe_evenement',
        ),
    ]
