# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('adresse', models.CharField(blank=True, max_length=1000, null=True)),
                ('lieu_geo_lat', models.FloatField()),
                ('lieu_geo_long', models.FloatField()),
                ('temps_rappel', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('mdp_hashe', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=12)),
                ('possede_appli', models.BooleanField()),
                ('position_actuelle_lat', models.FloatField(blank=True, null=True)),
                ('position_actuelle_long', models.FloatField(blank=True, null=True)),
                ('derniere_position_lat', models.FloatField(blank=True, null=True)),
                ('derniere_position_long', models.FloatField(blank=True, null=True)),
                ('temps_position_active', models.PositiveIntegerField(default=60)),
                ('amis', models.ManyToManyField(to='BDlove.Utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_createur', to='BDlove.Utilisateur'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(to='BDlove.Utilisateur'),
        ),
    ]
